### ISSUE TITLE
Running two spaces on the same machine

### ISSUE THREAD

**Issue by nkabir** [dancres/blitzjavaspaces#1]
I'd like to run two spaces on a single host--one space for testing (transient) and the other for local development (persistent). I'd also like to use unicast discovery. Is it possible to configure one Blitz space to run at 4160 and another at 4162?

**Comment by dancres** [comment]
If all you want is to run two spaces on the same machine you don't need to configure individual ports for Blitz it'll pick independent ones for itself (default configuration).

You would however have to have separate configuration files per Blitz instance because you want different storage options and you'll almost certainly want to set their names to different things.

Unicast discovery (and indeed multicast) both require you to run a Reggie (Lookup Service instance) which by default runs on port 4160. You could arrange for each Blitz to register via unicast (that requires you set the initialLocators configuration variable - see here: http://www.dancres.org/bjspj/docs/docs/install_guide.html#appb to point at the Reggie address).

You would also need to ensure your clients were given a LookupLocator to connect to the Reggie instance - that can be done in code if you wish.

BUT, I'm wondering why you want unicast discovery? Multicast should work just fine generally.

If you are using the installer, much of what you need can be found in scripts and configuration files bundled in the distribution (there's a readme.txt that explains what needs doing).

**Comment by nkabir** [comment]
_BUT, I'm wondering why you want unicast discovery? Multicast should work just fine generally._

Multicast does indeed work. However, for a group of developers working on the same subnet, won't multicast return spaces from other machines?

**Comment by dancres** [comment]
Consider the use of groups for segmentation of lookup services and services: http://river.apache.org/doc/specs/html/discovery-spec.html

Assign each developer a group of their own (say their initials if that gives you uniqueness), configure Reggie for that and each Blitz instance (done via initialGroups config variable). Done.

**Comment by nkabir** [comment]
I appreciate your suggestion--when helping colleagues debug their services, a group adds another parameter to the mix. Given the potential complexity of the set up, I thought that using localhost everywhere during development would avoid headaches.-)

**Comment by dancres** [comment]
"Given the potential complexity of the set up, I thought that using localhost everywhere during development would avoid headaches.-)"

Totally understand - from long painful experience I can highly recommend not going anywhere near localhost - get the groups thing and indeed use of the "right" machine names (not localhost) and such sorted early with scripting or tools or whatever. Leave it until later and it will _hurt bad_ much worse than doing the "right" thing now. Doing it now means a bit more early pain and some education/learning but that's way better than what comes from leaving it late. 

It's kind of a fundamental most fall foul of. Jini/River is a _very_ network centric piece of infrastructure, avoiding the complexities of networks via localhost directly conflicts with that and can hide away a bunch of nasty network problems you're better off knowing about early (many examples of messed up DNS configs and such that cause havoc when moving to test environments and production).

**Comment by nkabir** [comment]
Ah--good point! I've noticed many of those questions on the mailing lists.
